version: "3.8"
services:
  scraper:
    build: .
    container_name: waze_scraper
    volumes:
      - ./storage:/app/storage        # Monta la carpeta local storage en el contenedor
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis             # Host de Redis (nombre del servicio)
      - REDIS_PORT=6379
    networks:
      - waze_net

  redis:
    image: redis:latest
    container_name: waze_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - waze_net

networks:
  waze_net:

volumes:
  redis-data:
